import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { CopyRight } from "@/components/copy-right";
import { ScrollUp } from "@/components/scroll-up";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${inter.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="m-auto lg:py-8 lg:px-8 p-4 flex justify-end items-center">
            <ModeToggle />
          </header>
          <main className="font-[family-name:var(--font-inter)] max-w-3xl m-auto py-4 px-4 min-h-svh">
            {children}
          </main>
          <footer className="m-auto lg:p-8 p-4 flex justify-between items-center">
            <CopyRight />
            <ScrollUp />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
